// <auto-generated />
namespace MVCCodeFirst.Data.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Data1231 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Data1231));
        
        string IMigrationMetadata.Id
        {
            get { return "201810040914427_Data1231"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
